### ISSUE TITLE
Review of dts:citeDepth and dts:level

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#135]
Implementing the client, I found many inconsistencies and lack of clarity about the `dts:citeDepth` and `dts:level` properties, and the effect of the `level` parameter when used on references and range. 

I think it warrants one or two sentences to clarify situations.

If someone wants to take a shot at it ...

**Comment by PonteIneptique** [comment]
HI there, question for y'all : 

**Situation:**

In navigation, I can do `?ref=1&level=2`. What do I get ?

**Expected:**

- 2 levels below ref=1, which would be level 3 from root. ie 1.1.1
- 2 levels below the root, which would be 1 level below ref=1, ie 1.1

Not sure of the answer.

**Comment by balmas** [comment]
I would expect the latter: 2 levels below the root, which would be 1 level below ref=1, ie 1.1

**Comment by hcayless** [comment]
I agree with @balmas. `ref` is basically a filter—"I want only the 2-level citations that start with '1'".

**Comment by jonathanrobie** [comment]
Current semantics:

- dts:citeDepth  = maximum depth of the document tree - the maximum depth that occurs .
- dts:level = level of the identifier relative to the root, refers to the level of the members, not of the object itself.
-  ?level parameter = unclear semantics - is it absolute or relative? or does it refer to the number of levels to return in a given query?

Issues:

- dts:level can be confusing because it refers to the level of the object's members, not of the object itself.

**Comment by jonathanrobie** [comment]
1. Rename dts:citeDepth => dts:maxCiteDepth, with no change in meaning - it defines the maximum depth of the document.
2. dts:level describes the level of the identifier relative to the root. In the object, it is the level of the reference that was requested, which corresponds to the object itself.  dts:level is also repeated in the metadata for each member in the object.

**Comment by monotasker** [comment]
Addressed with pull request #208
