### ISSUE TITLE
Lurking ontological horrors

### ISSUE THREAD

**Issue by hcayless** [distributed-text-services/specifications#144]
I'm working on #139 and having to wrestle with the ontology behind Hydra. It is painful. hydra:title and hydra:description are Annotation Properties, meaning their proper use is in documenting aspects of Hydra, not to represent titles or descriptions of objects returned by a Hydra API (unless they are documentation). We probably need to define our own DTS properties for them (or re-use DC).

**Comment by PonteIneptique** [comment]
That's actually to some extent a pretty good news. This would avoid duplication and allows for direct and nice I18n without having to look in different places. We could probably withdraw `dct:title` from `dts:dublincore` and have `dct:description` stay there ?

As long as we're gonna have our own `@vocab`, should we go the way of LinkedArts and IIIF and avoid every prefixes for basic data, so that people could nearly not care about the LD in JSON-LD ?

**Comment by PonteIneptique** [comment]
One of my action items for today was to have a check on that.

I do think we need to go back from using hydra:title/description, but that's not really a bad thing in itself. It's not gonna be an awful moment I believe.

What I think this also pushes for is developing a "vocabulary" (do not know if ontology is the right word here) that defines our properties. If you look at http://www.markus-lanthaler.com/hydra/console/?url=http://www.markus-lanthaler.com/hydra/api-demo/ , you will see how the `@contexts` are built. I think it would be a good action item for us to build those contexts for people to have smaller responses.

**Comment by PonteIneptique** [comment]
So, basically, we can close this one I think and go back to #139
