### ISSUE TITLE
add missing citeType parameter to Document endpoint?

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#147]
Use case: a document uses multiple citation hierarchies - e.g. chapter/verse and page/folio

The Collections response includes a dts:citeStructure to hold the declared citation tree for the collection. This is defined to be a list, so it can hold multiple nested structures:

e.g.

```
"dts:citeStructure": [
  {
    "dts:citeType": "chapter",
       dts:citeStructure": [
         {
           "dts:citeType": "verse"
         }
       ]
   },

  {
    "dts:citeType": "page",
       dts:citeStructure": [
         {
           "dts:citeType": "folio"
         }
       ]
   },

]
```

And then in the navigation response, the references in the member element can include the dts:citeType property to offer the different options:

```
 "member": [
      { "ref": "53", "dts:citeType": "chapter"},
      { "ref": "1" , "dts:citeType": "page"},
      // And so on
    ],
```

BUT in the Documents endpoint, there is currently no place to specify the `citeType`, so it is left ambiguous which citeType it might refer to.  I.e. we have a `ref` query parameter but no accompanying `citeType` parameter.

**Comment by PonteIneptique** [comment]
I think this issue is particularly right when two or more identifier collides (line 1 vs. page 1).

One way to deal with it, right now, for implementers is to prefix those identifiers (l1 vs p1) which is not perfect.

Note that we might want to think about the implication, this might lead to having : 

- `ref=`
- `refType=`
- `start=`
- `startType=`
- `end=`
- `endType=`

if we push this capacity to its limit.

**Comment by PonteIneptique** [comment]
**Issue with the current situation**
Stated by @balmas 

**Issues about implementation a response to the issue**
The form of the Document endpoint requires one version in XML TEI but we cannot depend on it. 
Do we need something that is valid cross-media-type ?

**Potential solutions**
1. Not caring about non-TEI or XML data and just provide a new attribute in the `<dts:fragment>` node.
2. Add a new range of `DTS-` prefixed headers specific to our API.
3. Find a generally accepted Header key which could accept the information

**Comment by PonteIneptique** [comment]
In the DTS RC workshop of Durham, it was decided that:
-  `citeType` must be provided for any `CitableUnit`.
- no filtering operation can be operated on `citeType` with query parameters.
- each `CitableUnit` identifier should be unique within a `CitationTree`
- `CitationTree` and `?tree` can be used for competing `CitableUnit` identifier such as paragraph 1 and page 1.

**Comment by kbrueckmann** [comment]
I'm wondering why `citeType` wouldn't be used as a query parameter. I think that such a parameter would be incredibly useful for many use cases and definitely lessen the work needed for tasks like getting only the verse lines from a TEI document for an analysis.

This is especially true for documents that are unevenly structured (of which we have many...) because there doesn't seem a way around some fiddling outside of DTS otherwise. Just to illustrate:

Our documents might look like this:
- chapter A
  - section 1
    - verse line 1
    ...
  - section 2
    - verse line 1
    …
- chapter B
  - verse line 1 
  …

With some chapters having sections and others not, our citationTree should look like this and show the deepest possible structure (I think):
```json
  "citationTrees": [
    {
      "@type": "CitationTree",
      "citeStructure" : [
        {
          "citeType": "chapter",
          "citeStructure": [
            {
              "citeType": "section"
              "citeStructure": [
                {
                  "citeType": "verse-line"
                }
              ]
            }
          ]
        }
      ]
    }
  ] 
```
Seeing this, users might try a query on chapter-level with a down-value of 2 and get all the verses – but also all the chapter nodes between start and end as the citation tree between those should be included in the output.

So the user would have to filter the list of received CitableUnits by their citeType manually (meaning programmatically, but outside of DTS), extract the identifiers and construct multiple links to query the document endpoint with to actually get the wanted results. I don't see a way around this without a citeType-parameter, but I might have also misunderstood parts of the specs.
