### ISSUE TITLE
Use Case L2: Query if a work is available

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/specifications#16]
Some questions about https://github.com/distributed-text-services/API/blob/master/userstories.csv#L2
- how does the user identify a work? Two approaches seem equally useful:
  - navigationally: 'list all works', select a specific work based on metadata
  - based on a known name or identifier
- what does the user get when they "retrieve a work"?  what is a "work"?
  - metadata describing an edition?
  - the edition itself?
- Do all searches return collections of 'descriptions', or do searches with unique results simply return the result?

**Comment by jeffreycwitt** [comment]
Regarding the second bullet point: "What is a work" and what "metadata" should be returned.

Because the CTS model identifies Version with FRBR Expression but makes no mention of a FRBR Manifestation, you might expect a Work to return a list of available "Versions". But I think Versions should be identified with FRBR Manifestations and Expressions should be reserved for a concept between Works and Versions/Manifestations. See my use case [https://github.com/distributed-text-services/API/issues/18](https://github.com/distributed-text-services/API/issues/18)

Thus I would like to see a Work return the following properties

- type=work
- label
 - e.g. Adam Wodeham Ordinatio, Moby Dick
description 
- author 
- workType (available workTypes should be determined by the available workTypes specified by the WorkGroupType) 
 - e.g. Novel
 - e.g. SentencesCommentary
 - e.g. BiblicalCommentary
citation
 - e.g Epic Poem
- hasExpression
- hasCanonicalExpression
 - since there can be more than one expression, I would like to know which expression is privileged as the default expression to use.
- hasCanonicalTranscription
 - since there might be a lot of levels between an abstract work and a canonicalTranscription of that work, I would like to see the Work list a privileged transcription that client can default to.

BTW: I tried to provide an answer to the kind of metadata I would like to see accompany each CTS/FRBR resource. My working list is here [https://github.com/jeffreycwitt/scta-ontology/blob/master/SCTAOntologySpec.md](https://github.com/jeffreycwitt/scta-ontology/blob/master/SCTAOntologySpec.md)

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
