### ISSUE TITLE
fix documentation of collection/collections link relation

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#170]
@balmas

> 3. In the documents endpoint, the link header for the collection itself uses "collection" in the documentation we have "collections". I think actually "collection" singular does make more sense.

@zfletch

>I'm actually pretty confused about which one is correct to use here. The [documentation](https://distributed-text-services.github.io/specifications/Documents-Endpoint.html) says `collections` in the table near the beginning, but the examples all use `collection`. Does the table take precedence over the examples in the documentation?

(The reason this implementation used `collection` is because I wrote this implementation by copying and pasting each example into a test file then writing code to make the test pass.)

_Originally posted by @zfletch in https://github.com/distributed-text-services/specifications/issues/163#issuecomment-543896066_

**Comment by PonteIneptique** [comment]
So, the history behind this choice is the following : https://tools.ietf.org/html/rfc6573 specifies a `collection` rel which we ended up reusing.

This seems do be due to an unwanted fix nobody catched during this commit : https://github.com/distributed-text-services/specifications/commit/0a61664dc240f3d66acf07f114c751d5ad1c369b#diff-c7398a3be3ddc76622d7c2c78ec3b6aeR57

**Comment by monotasker** [comment]
That's consistent with what I'm doing with the revised document endpoint docs (document rather than documents)
