### ISSUE TITLE
Naming authorities and Identity URNs

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/specifications#32]
In last week's telcon, we discussed the need to allow various groups to define their own URNs for resources using a structure like this:

`urn:dts:{authority}:{identifier}`

The naming authority defines the format of the identifier, which may be a single token or a path of colon delimited tokens. Groups who work with similar sets of documents may choose to use a common naming authority to capture commonality.

**Comment by balmas** [comment]
@jonathanrobie I think the spec supports this. Can you confirm that your need is met?

**Comment by PonteIneptique** [comment]
I want to put an update here.

I think we need, in regard to what @PietroLiuzzo is doing, to be able to reserve the dts namespace and provide a resolver for this.

I would like to have reserved provider namespaces, so that project like BetaMasaheft register urn:dts:betamasaheft and any query on a urn from this space would be redirected to his API. The app could then be a simple list of namespaces -> API Addresses, like the system of w3id.org.

A project could, if they'd want to, host multiple namespaces. And we could accept "fallback" providers.

**Comment by balmas** [comment]
If we do this, I'd like to seriously consider a handle system  based approach to providing a resolver. I don't think we should be developing a new PID resolver solution.

**Comment by PonteIneptique** [comment]
I'd be fine with this option, I think :D

**Comment by monotasker** [comment]
We decided that we won't implement this
