### ISSUE TITLE
Members and Files

### ISSUE THREAD

**Issue by hcayless** [distributed-text-services/specifications#39]
This is a question I wanted to ask in the meeting, but we ran out of time: Are files (e.g. TEI files) just members of a collection? in my proposal, I'd envisioned the collections API stopping at a "resource", which would then have a property that gave you access to the files. From the Swagger spec, I take it that there'll be something like:

````js
"members": {
  "contents": [
    {
      "@id": "http://example.com/foo.xml"
    },
    {
      "@id": ""http://example.com/foo.txt"
    },
    {
      "@id": ""http://example.com/foo.html"
    }
  ]
}
````
I'm not altogether happy with this. I worry about two things: file metadata is going to be different from abstract thing metadata, but also, (I think Jeff alluded to this a while ago) what if you had a setup where there were lots of little TEI files that you aggregate into a corpus (think books of the Iliad where each book is a file and then there's a master file that XIncludes all of them)? So the "Iliad" might be both a file and a collection. Is the master file just another member? Am I nuts to worry about this stuff?

**Comment by balmas** [comment]
You are never nuts @hcayless :-) 

A couple of thoughts.

1. I think members probably need another property, `location` to identify the location at which the resource can be retrieved. In many cases this will be the same as the id but it might not be in all cases.

2. We could think of the thing that is implemented via  multiple files a collection of files couldn't we? In which case its members would be the individual files and their locations.

3. I think this also explains why we need both type and model, something I dropped in the swagger spec  after the discussion in #38 but would like to put back.  Something could be of a specific type, such as a cts:edition, and be modelled as a collection or a resource.

i.e, we might have a sequence of requests:

```
/collections/urn:cts:tlg0012.tlg001

{
  members: [
    {
      "@id" : "urn:cts:tlg0012.tlg001.perseus-grc1",
      "location": "http://passage_api_endpoint/urn:cts:tlg0012.tlg001.perseus-grc1",
      "type": "http://homermultitext.org/rdfvocab/edition",
      "model": "http://dts.org/vocab/collection"
    }
  ]
}
```

You have the location that you can to go to directly retrieve this edition from its cts endpoint if you want, but because the dts api tells you it's a collection, you know you can query it further that way

```
/collections/urn:cts:tlg0012.tlg001.perseus-grc1

{ ...
   members: [
    {
      "@id" : "urn:cts:tlg0012.tlg001.perseus-grc1.1/xml",
      "location": "http://github.com/PerseusDL/canonical-greekLit/data/tlg0012.tlg001.perseus-grc1.1.xml',
      "type": "<ideally a uri identifying a tei xml data type>'
      "model": "http://dts.org/vocab/resource"
    },
    {
      "@id" : "urn:cts:tlg0012.tlg001.perseus-grc1.2/xml",
      "location": "http://github.com/PerseusDL/canonical-greekLit/data/tlg0012.tlg001.perseus-grc1.2.xml',
      "type": "<ideally a uri identifying a tei xml data type>'
      "model": "http://dts.org/vocab/resource"
    }

  ]  
..}
```
Now this returns a resource, and it's made up of multiple xml files

Does this make sense? Have I understood the question correctly?

**Comment by PonteIneptique** [comment]
If I forget to reply, please ping me. I need to chime in here but it's too
late my time :')

Le 25 janv. 2017 10:05 PM, "Bridget Almas" <notifications@github.com> a
écrit :

You are never nuts @hcayless <https://github.com/hcayless> :-)

A couple of thoughts.

   1.

   I think members probably need another property, location to identify the
   location at which the resource can be retrieved. In many cases this will be
   the same as the id but it might not be in all cases.
   2.

   We could think of the thing that is implemented via multiple files a
   collection of files couldn't we? In which case its members would be the
   individual files and their locations.
   3.

   I think this also explains why we need both type and model, something I
   dropped in the swagger spec after the discussion in #38
   <https://github.com/distributed-text-services/collection-api/issues/38>
   but would like to put back. Something could be of a specific type, such as
   a cts:edition, and be modelled as a collection or a resource.

i.e, we might have a sequence of requests:

/collections/urn:cts:tlg0012.tlg001

{
  members: [
    {
      "@id" : "urn:cts:tlg0012.tlg001.perseus-grc1",
      "location":
"http://passage_api_endpoint/urn:cts:tlg0012.tlg001.perseus-grc1",
      "type": "http://homermultitext.org/rdfvocab/edition",
      "model": "http://dts.org/vocab/collection"
    }
  ]
}

You have the location that you can to go to directly retrieve this edition
from its cts endpoint if you want, but because the dts api tells you it's a
collection, you know you can query it further that way

/collections/urn:cts:tlg0012.tlg001.perseus-grc1

{ ...
   members: [
    {
      "@id" : "urn:cts:tlg0012.tlg001.perseus-grc1.1/xml",
      "location":
"http://github.com/PerseusDL/canonical-greekLit/data/tlg0012.tlg001.perseus-grc1.1.xml',
      "type": "<ideally a uri identifying a tei xml data type>'
      "model": "http://dts.org/vocab/resource"
    },
    {
      "@id" : "urn:cts:tlg0012.tlg001.perseus-grc1.2/xml",
      "location":
"http://github.com/PerseusDL/canonical-greekLit/data/tlg0012.tlg001.perseus-grc1.2.xml',
      "type": "<ideally a uri identifying a tei xml data type>'
      "model": "http://dts.org/vocab/resource"
    }

  ]
..}

Now this returns a resource, and it's made up of multiple xml files

Does this make sense? Have I understood the question correctly?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/distributed-text-services/collection-api/issues/39#issuecomment-275232712>,
or mute the thread

**Comment by PonteIneptique** [comment]
> 1. I think members probably need another property, `location` to identify the location at which the resource can be retrieved. In many cases this will be the same as the id but it might not be in all cases.

Agree, I have been advocating for it. But not sure we understand the same thing by it.

> 2. We could think of the thing that is implemented via  multiple files a collection of files couldn't we? In which case its members would be the individual files and their locations. 

Disagree. Because if we do, we start to create imbalance between passage API and collection. This however could be done at the last stage of the collection by making something like the following. Otherwise, this would complicate things unnecessarily (we already are diving in deep waters, compared to simple APIs such as CTS).  

> 3. I think this also explains why we need both type and model, something I dropped in the swagger spec  after the discussion in #38 but would like to put back.  Something could be of a specific type, such as a cts:edition, and be modelled as a collection or a resource.

Agree, but added static and interactive as subcategories

```json
{
"@id" : "urn:cts:tlg0012.tlg001.perseus-grc1",
"interfaces": [
    {
      "location": "http://github.com/PerseusDL/canonical-greekLit/data/tlg0012.tlg001.perseus-grc1.xml",
      "type": "xml:tei",
      "model": "http://dts.org/vocab/static-resource"
    },
    {
      "location": "/api/dts/references/urn:cts:tlg0012.tlg001.perseus-grc1",
      "type": "xml:tei",
      "model": "http://dts.org/vocab/interactive-resource"
    }
]
}
```
Instead of members because we are at the reading level of the collection hierarchy.

**Comment by hcayless** [comment]
My hesitation is that when we get to the retrieval of actual, readable texts, we're transitioning from (in Dublin Core terms) hasPart to hasFormat (though there's more to it than that too). Would MIME type be sufficient for type?

**Comment by PonteIneptique** [comment]
I am a bit lost on that because I think we agreed that retrieval would be dependant on another part of the API, ie the "passage" and "referencesList" one. There you could request mime types for the retrieval (given that it would be advertised by the API).

We could also support different kind (interactive and static) interfaces for the text, hence not members but interfaces.

**Comment by hcayless** [comment]
I guess you could argue that files are the end point of the collections API and the starting point of the passages API. I'm inclined to say that the two APIs have to dovetail, but where they come together might differ according to the collection setup. If I can't navigate to resources with the collections API though, is it really useful? Can it only give me the structure of the collection, and then it has to hand off to another API?

**Comment by PonteIneptique** [comment]
Well with my example, you can navigate up to the resource (whether static or interactive). However, the splitting of said resource (for what would be interactive like mimetype and stuff) should I think be something for the Passage API.

**Comment by balmas** [comment]
I think we may need to get further into the requirements and spec for the passage api before we can come to a resolution on this.

**Comment by PonteIneptique** [comment]
For cleaning reason, we are closing old issues.
Please feel free to comment if you think we should reopen.
