### ISSUE TITLE
Should we have standard metadata items for providing language of the collection?

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#51]
@PietroLiuzzo 's question about how to use the label and lang elements makes me realize we may be missing this in the current version of the spec.
We currently have an `@rdfs:label` property on a collection, which itself contains  `lang` and `value` keys, but this is not intended to represent the language of the described collection, or member, just the language of the label itself.

Do we want to add `language` as a property on a collection as with `description` in #44 ?

(@PietroLiuzzo let me know if I misunderstood your question)

**Comment by PonteIneptique** [comment]
Well it definitively makes sense for the ResourceCollection object (the one which is both a colleaction and readable :) )

**Comment by jeffreycwitt** [comment]
If a translation is just another version of a work (CTS language) or just another manifestation of an expression (FRBR language), then I think the appropriateness of a lang property depends on where we are in the collection. 

If the resource in question is a "cts:version"/"frbr:manifestation" then it could have a language. But if the resource is a "cts:work/frbr:expression" I don't think a language property is appropriate because the resource in question is still an abstract idea that is yet to be instantiated into a given text in a given language.

**Comment by PonteIneptique** [comment]
Agree with @jeffreycwitt but !
If we'd be going with #52, dc:language could be multiple (! huge difference with CTS) and also describe the language spoken by an individual for example (collection->Seneca, language->Latin).

**Comment by balmas** [comment]
I suggest we add it, per #52, and make it optional.

**Comment by jonathanrobie** [comment]
As long as you can have multiple languages, I like it.  Optional is fine.

**Comment by PonteIneptique** [comment]
Implemented through dts:dublincore
