### ISSUE TITLE
Mean to differenciate a metadata-only collection and a readable collection

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/specifications#54]
# Problem

This is quite connected to the https://github.com/distributed-text-services/references-api and https://github.com/distributed-text-services/passage-api but needs to be solved here. The question is simple : how do you know when a resource is readable in validReff ?

# Solution 1 : dts:type

And dts:readableCollection, dts:collection, dts:staticCollection. In this case, we introduce a dts:type predicate, which would have as default value dts:collection. We can then extend to dts:readableCollection for collection that are usable through the two other APIs while dts:staticCollection could be created (I can't find the use case of @jeffreycwitt that was connected to this) to link to static content representing the given object.

# Solution 2 : dts:readable

I assume it would connect to the roles (@balmas ?) but roles are still not clear to me. This predicate, with value false by default, would mean, when set to true, that the object can be browsed in the ref and passage API .

**Comment by balmas** [comment]
Ah it seems this might be a duplicate of #39, or at the very least, related?

**Comment by PonteIneptique** [comment]
It definitely is overlapping. Could we discuss that in the meeting ?

**Comment by hcayless** [comment]
We haven't gotten back around to reference syntax, but I would think the answer would be better given at the level of item metadata rather than collection. I can easily imagine a case where you have a pretty full catalog of works, but only a few digital editions.  Put another way, a sparse collection is likely to be a more common thing than an empty one. If we have some flag saying "digital edition available", then you'd be able to query on that and see if a given collection has any files for you. Actually, that flag is probably `dc:hasFormat`.

**Comment by balmas** [comment]
I understood this a bit differently.  @PonteIneptique are you trying to use this to distinguish between collections which can be navigated using the references API and those that cannot?  I.e. the difference between a collection of editions of a work, and a collection which is itself an edition of a work?

**Comment by PonteIneptique** [comment]
@balmas Cannot say that better :) It's exactly that. "Interactively Readable Text Collections" would be the term, vs "Metadata Collection [Or Collections Container]"

**Comment by PonteIneptique** [comment]
Now possible with Hydra. Fixed.
