### ISSUE TITLE
Description of the project

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/specifications#71]
_From @PonteIneptique on May 25, 2016 12:52_

_Copied from original issue: distributed-text-services/distributed-text-services.github.io#2_

**Comment by PonteIneptique** [comment]
I want to reactive this issue because it was clearly the case 10 days ago that this is not clear for everyone, and as such, even if it takes few minutes, the goals of DTS should be made clear by the group. Here is my POV.

# The CTS issue

The original scope of the discussion, started a couple years ago I think (...), was to address the limitations and failure of CTS : 
1. its identifier system which forced a modelisation that was impossible to put on any kind of resources
2. its metadata scheme that had the same bias (which is normal because it's based on the identifier)
3. its absence of will to evolve to scale better (*ie* a getvalidreff on the illiad http://cts.perseids.org/api/cts/?request=GetValidReff&urn=urn:cts:greekLit:tlg0012.tlg001&level=2 and the lack of optimization of such a response)
4. its unability to clearly state response types : the response should be formated into XML (see response scheme that were enforced) but the content of `<passage>` node were untyped

# Scope of the original discussion at Tufts
*During a december meeting (I let @balmas put the right date here if she can remember it)*, we discussed this issue with a group of people who where interested by CTS but could not apply it to their corpus. The common feature of this group was the need to serve text or chunk of texts that were editions. This included editorialized texts such as Perseus' editions or critical edition of texts.

# Proposal of definition
*Albeit it might not be proper English and might need correction from the native speakers*

> The Distributed Text Services' standard for web API (DTS API) is focused on uniforming the browsing and retrieval of textual edition at different scope in digital open formats. As such, it proposes ways to browse the catalog of a repository, the structure of editions and retrieve them, as full or partial content.
> Historically, the DTS API is an evolution of the Canonical Text Services 5.0 and is as such retro-compatible with its features. Unlike the former, the DTS API strives to be opened to many different kind of texts and does not assume any kind of modeling of one's repository's catalog nor does it enforces an identifier system.

Until a decision is reached on base format, I'll keep the line out but I think it would be cool to add something about TEI in the first paragraph.

**Comment by balmas** [comment]
The original meeting was a roundtable November 4, 2015 at Tufts
Original documents, including notes from the roundtable, and initial meetings, can be found in the slack group  https://distributedtext.slack.com

Worth looking at perhaps:
https://distributedtext.slack.com/files/U0DDWPWUU/F0E50R18X/Decisions_action_items_from_first_roundtable
https://distributedtext.slack.com/files/U0DDWPWUU/F0DS3B44X/API_Desiderata

**Comment by balmas** [comment]
I think PR #122 and #126 address this adequately for now and recommend that this can be closed.
