### ISSUE TITLE
Endpoint of the root-level collection as entry point for the API

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/specifications#93]
Should the endpoint of the root-level collection be the entry point for the API?

**Comment by PonteIneptique** [comment]
Actually, I just remembered the argument.
If someone is browsing, say, Ecole des Chartes resources on the website (Not API). They know of the DTS api but not necessarly the routes. Because our endpoints are not fixed in terms of URIs, it would mean they need to take one step more to know the URI of the passage (namely, retrieve the collection in the collection api to know the document endpoint URI).

If it's not clear, I'll draw something :)

**Comment by PonteIneptique** [comment]
Issue closed for the first publication draft. Possible to reopen if you think this is not addressed.
--
